---
title: "git_01"
author: "Marina"
date: "Spring semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
’Twas brillig, and the slithy toves  
Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
And the mome raths outgrabe.  

“Beware the Jabberwock, my son!  



## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
“The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —  
And this was odd, because it was  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done —  
“It’s very rude of him,” she said,  
“To come and spoil the fun.”  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
You’re winning. You simply cannot fail.  
The only obstacle is doubt;  
There’s not a hill you cannot scale  
Once fear is put to rout.  

Don’t think defeat, don’t talk defeat,  
The word will rob you of your strength.  
“I will succeed,” This phrase repeat  
Throughout the journey’s length.  

The minute that “I can’t is said –  
You slam a door right in your face.  
Why not exclaim, “I will” instead?  
Half won then is the race.  

You close the door to your success  
By entertaining one small fear.  
Think happiness, talk happiness,  
Watch joy then coming near.  

The word “impossible” is black.  
“I can” is like a flame of gold.  
No whining, heart! Eyes! look not back;  
Be strong, O Will! and bold.  